### switch default prefix to C-a
unbind C-b
set -g prefix C-a

### useful custom keybindings
### "C-a a" sends C-a
bind-key a send-prefix
### killing pane and session interactively
bind-key k confirm-before kill-pane
bind-key K confirm-before kill-session
### reload config
bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded"
### (more) easily switch from one window or pane to an other
bind -n f1 previous-window
bind -n f2 next-window
bind -n f3 select-pane -t :.-
bind -n f4 select-pane -t :.+
### toggle synchronize-panes (send command to all panes)
bind S setw synchronize-panes
### toggle mouse on, or off
bind m setw -g mouse on \; display 'mouse: on'
bind M setw -g mouse off \; display 'mouse: off'
### create new ssh connection naming the window according to the target host
bind R command-prompt -p "ssh:" "new-window -n %1 '/usr/bin/ssh -A -q %1'"

### misc options
set -g default-terminal "screen-256color"

### monitor activities in other windows
setw -g monitor-activity on
set -g visual-activity on

### use vi keys in buffer
setw -g mode-keys vi

### general status bar settings
set -g status-style bg=yellow,fg=white
set -g window-status-current-style bg=white,fg=red,underscore
### status-left: @hostname:[sessionname]
set -g status-left-length 20
set -g status-left "@#h:[#S]   "
### status-right: date and time
set -g status-right-length 20
set -g status-right '   %Y-%m-%d %H:%M'

### maximum number of lines held in window history
set -g history-limit 50000